package com.api.domaine.assertions.credentials;

import com.api.domaine.credentials.CredentialsForSignIn;
import org.assertj.core.api.AbstractAssert;

/**
 * {@link CredentialsForSignIn} specific assertions - Generated by CustomAssertionGenerator.
 */
public class CredentialsForSignInAssert extends AbstractAssert<CredentialsForSignInAssert, CredentialsForSignIn> {

  /**
   * Creates a new <code>{@link CredentialsForSignInAssert}</code> to make assertions on actual CredentialsForSignIn.
   * @param actual the CredentialsForSignIn we want to make assertions on.
   */
  public CredentialsForSignInAssert(CredentialsForSignIn actual) {
    super(actual, CredentialsForSignInAssert.class);
  }

  /**
   * An entry point for CredentialsForSignInAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myCredentialsForSignIn)</code> and get specific assertion with code completion.
   * @param actual the CredentialsForSignIn we want to make assertions on.
   * @return a new <code>{@link CredentialsForSignInAssert}</code>
   */
  public static CredentialsForSignInAssert assertThat(CredentialsForSignIn actual) {
    return new CredentialsForSignInAssert(actual);
  }

}
